/// Embed the Windows exe/taskbar icon (brand pass, 2026-07-03): the multi-res
/// `assets/branding/yt-clipper.ico`, generated by `scripts/render-brand.ps1`
/// from the "Punch-out" master (`assets/branding/logo.svg`). Skipped quietly
/// when the ico is absent so a slim checkout still builds.
fn main() {
    #[cfg(windows)]
    {
        let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let ico = std::path::Path::new(&manifest).join("../../assets/branding/yt-clipper.ico");
        println!("cargo:rerun-if-changed={}", ico.display());
        if ico.is_file() {
            let mut res = winresource::WindowsResource::new();
            res.set_icon(&ico.to_string_lossy());
            if let Err(e) = res.compile() {
                println!("cargo:warning=exe icon embed failed: {e}");
            }
        }
    }
}
